### ISSUE TITLE
Not working with wsgi

### ISSUE THREAD

**Issue by tuchinsky** [jirutka/change-password#8]
Hello, I Apache with this config (I also tried nginx+uwsgi and the result is the same):

```
<VirtualHost passwd.example.org:80>
	ServerName passwd.example.org
	WSGIDaemonProcess change-passwd user=apache group=apache processes=1 threads=5
	WSGIScriptAlias / /var/www/html/change-passwd/app.py

	<Directory /var/www/html/change-passwd>
		WSGIProcessGroup change-passwd
		WSGIApplicationGroup %{GLOBAL}
		Require all granted
	</Directory>
</VirtualHost>
```

Apache successfully started and display main page, but if I try change password I get error "Error: 500 Internal Server Error":

```
[Fri Jul 07 13:18:21.143218 2017] [:error] [pid 106200] [remote 172.30.0.10:34204] Traceback (most recent call last):
[Fri Jul 07 13:18:21.143268 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/bottle.py", line 861, in _handle
[Fri Jul 07 13:18:21.143273 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     return route.call(**args)
[Fri Jul 07 13:18:21.143275 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/bottle.py", line 1731, in wrapper
[Fri Jul 07 13:18:21.143278 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     rv = callback(*a, **ka)
[Fri Jul 07 13:18:21.143281 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/var/www/html/change-passwd/app.py", line 34, in post_index
[Fri Jul 07 13:18:21.143284 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     change_password(form('username'), form('old-password'), form('new-password'))
[Fri Jul 07 13:18:21.143287 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/var/www/html/change-passwd/app.py", line 65, in change_password
[Fri Jul 07 13:18:21.143290 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     change_password_ad(*args)
[Fri Jul 07 13:18:21.143292 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/var/www/html/change-passwd/app.py", line 94, in change_password_ad
[Fri Jul 07 13:18:21.143295 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     c.extend.microsoft.modify_password(user_dn, new_pass, old_pass)
[Fri Jul 07 13:18:21.143298 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/ldap3/extend/__init__.py", line 265, in modify_password
[Fri Jul 07 13:18:21.143301 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     controls)
[Fri Jul 07 13:18:21.143303 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/ldap3/extend/microsoft/modifyPassword.py", line 50, in ad_modify_password
[Fri Jul 07 13:18:21.143306 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     controls)
[Fri Jul 07 13:18:21.143309 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 1044, in modify
[Fri Jul 07 13:18:21.143312 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     response = self.post_send_single_response(self.send('modifyRequest', request, controls))
[Fri Jul 07 13:18:21.143314 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 124, in post_send_single_response
[Fri Jul 07 13:18:21.143317 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     responses, result = self.get_response(message_id)
[Fri Jul 07 13:18:21.143320 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]   File "/usr/lib/python2.7/site-packages/ldap3/strategy/base.py", line 377, in get_response
[Fri Jul 07 13:18:21.143323 2017] [:error] [pid 106200] [remote 172.30.0.10:34204]     raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
[Fri Jul 07 13:18:21.143327 2017] [:error] [pid 106200] [remote 172.30.0.10:34204] LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - OU=ADM,OU=HQ,DC=alt,DC=altarix,DC=ru - 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of: 'OU=ADM,OU=HQ,DC=alt,DC=altarix,DC=ru'
```

But the password check is successful:

`[Fri Jul 07 13:18:08.841810 2017] [:error] [pid 106200] Unsuccessful attemp to change password for tak: Username or password is incorrect!`

Then an error occurs only when trying to change the password

**Comment by jirutka** [comment]
What version of change-password do you have? 1.0.0 or the current master? I should admit that I haven’t tried it against Samba/AD after updating to ldap3 2.x (current master).

This error is clearly not related to WSGI.

**Comment by tuchinsky** [comment]
I have current master

If start the application manually (chmod +x app.py && ./app.py) - all work fine. This problem only occurs when I start change-password with third-party apps (such as apache+mod_wsgi, nginx+uwsgi or simple systemd unit script)

**Comment by jirutka** [comment]
That’s really weird…

**Comment by tuchinsky** [comment]
Do you have any ideas?

**Comment by jirutka** [comment]
No idea. I’ve just deployed new version to Samba server and it works. However, I’ve switched from uWSGI to [Waitress](https://docs.pylonsproject.org/projects/waitress/) and run it using `waitress-serve`, started by OpenRC runscript.

* [OpenRC runscript for waitress](https://github.com/alpinelinux/aports/blob/master/community/py-waitress/waitress.initd)
* [runscript config for ldap-passwd-webui](https://github.com/alpinelinux/aports/blob/master/testing/ldap-passwd-webui/ldap-passwd-webui.confd)

If you use Alpine Linux, you can easily install it from the testing repository (and community/edge for py-waitress and py-ldap3); `apk add ldap-passwd-webui-waitress`, `rc-service ldap-passwd-webui start`.

**Comment by chienbinhso13** [comment]
My setting.ini
`
[html]
page_title = Change your password on example.org

[ldap]
host = abc.com
port = 636
use_ssl = true
base = ou=People,dc=abc,dc=com
;search_filter = uid={uid}

; Uncomment for AD / Samba 4
type = ad
ad_domain = DC-02.abc.com
search_filter = sAMAccountName={uid}

[server]
server = auto
host = localhost
port = 8080`

But when I try, I have an error
`C:\Users\userX\AppData\Local\Programs\Python\Python36-32\python.exe "C:/Users/userX/Desktop/Change pass/ldap-passwd-webui-master/app.py"
2017-07-14 17:40:22,223 INFO: Starting ldap-passwd-webui 2.0.0
Bottle v0.12.13 server starting up (using AutoServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

127.0.0.1 - - [14/Jul/2017 17:40:25] "GET / HTTP/1.1" 200 1350
Traceback (most recent call last):
  File "C:\Users\userX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Users\userX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:/Users/userX/Desktop/Change pass/ldap-passwd-webui-master/app.py", line 41, in post_index
    change_password(form('username'), form('old-password'), form('new-password'))
  File "C:/Users/userX/Desktop/Change pass/ldap-passwd-webui-master/app.py", line 72, in change_password
    change_password_ad(*args)
  File "C:/Users/userX/Desktop/Change pass/ldap-passwd-webui-master/app.py", line 98, in change_password_ad
    with connect_ldap(authentication=SIMPLE, user=user, password=old_pass) as c:
  File "C:\Users\userX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ldap3\core\connection.py", line 462, in __enter__
    self.open()
  File "C:\Users\userX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ldap3\strategy\sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "C:\Users\userX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ldap3\strategy\base.py", line 144, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(datetime.datetime(2017, 7, 14, 17, 41, 35, 617646), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket ssl wrapping error: [WinError 10054] An existing connection was forcibly closed by the remote host',), ('192.168.4.12', 636)), (datetime.datetime(2017, 7, 14, 17, 41, 35, 622646), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket ssl wrapping error: [WinError 10054] An existing connection was forcibly closed by the remote host',), ('192.168.4.11', 636))])
127.0.0.1 - - [14/Jul/2017 17:41:35] "POST / HTTP/1.1" 500 741`

I've try LDAP setting only but it í the same
